version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: 
          name: installing nomad
          command: |
            apt-get update && apt-get install nomad
      - run: 
          name: use vagrant
          command: |
          apt install curl
            mkdir nomad-demo
            cd nomad-demo
            curl -O https://raw.githubusercontent.com/hashicorp/nomad/master/demo/vagrant/Vagrantfile
            vagrant up
            nomad



workflows:
  build_and_test:
    jobs:
      - build
