version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - checkout
      - run: 
          name: installing nomad
          command: nomad agent -dev -log-level INFO
          background: true
      - run: sleep 30
      - run:
          name: running nomad
          command: |
            nomad job init
            nomad run example.nomad
            




workflows:
  build_and_test:
    jobs:
      - build

