version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: 
          name: installing nomad
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
            sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            sudo apt-get update && sudo apt-get install nomad
      - run: 
          name: use vagrant
          command: |
            mkdir nomad-demo
            cd nomad-demo
            curl -O https://raw.githubusercontent.com/hashicorp/nomad/master/demo/vagrant/Vagrantfile
            vagrant up
            nomad



workflows:
  build_and_test:
    jobs:
      - build
