version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: 
          name: installing nomad
          command: |
            apt-get -y update && apt-get -y install tzdata && apt-get -y install gnome-terminal && apt-get -y install nomad
      - run: 
          name: use vagrant
          command: |
            gnome-terminal
            nomad agent -dev -bind 0.0.0.0 -log-level INFO
      - run: 
          name: nomad
          command: |
            nomad job init
            nomad run example.nomad




workflows:
  build_and_test:
    jobs:
      - build
