version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - run: nomad job init
      - run: nomad start example.nomad

            
            


workflows:
  build_and_test:
    jobs:
      - build
