version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: 
          name: installing nomad
          command: |
            apt-get update -&& apt-get -y upgrade && apt-get -y install nomad && apt-get -n install gnome-terminal 
      - run: 
          name: use vagrant
          command: |
            gnome-terminal
            nomad agent -dev -bind 0.0.0.0 -log-level INFO
      - run: 
          name: nomad
          command: |
            nomad job init
            nomad run example.nomad




workflows:
  build_and_test:
    jobs:
      - build
