version: 2.1

jobs:
  build:
    steps:
      - run: 
          name: installing nomad
          command: |
            nomad job init
            nomad start example.nomad


workflows:
  build_and_test:
    jobs:
      - build
