version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - checkout
      - run: 
          name: installing nomad
          command: nomad agent -dev -log-level INFO
          background: true
      - run: sleep 30
      - run:
          name: running nomad
          command: |
            touch examp.nomad
            cp /exam.nomad examp.nomad
            nomad run examp.nomad
            




workflows:
  build_and_test:
    jobs:
      - build

