version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: 
          name: installing nomad
          command: |
            apt-get update -&& apt-get -y upgrade && apt-get -y install nomad
      - run: 
          name: use vagrant
          command: |
            nomad



workflows:
  build_and_test:
    jobs:
      - build
