version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - checkout
      - run: 
          name: installing nomad
          command: |
            apt-get -y update 
            apt-get -y install nomad && nomad agent -dev -bind 0.0.0.0 -log-level INFO
      - save_cache:
          keys: gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  deploy:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - checkout
      - run: sleep 30
      - restore_cache:
          keys:
            - gem-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - asset-cache-v1-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
            - asset-cache-v1-{{ arch }}-{{ .Branch }}
            - asset-cache-v1
      - run: nomad job init && nomad run example.nomad


workflows:
  build_and_test:
    jobs:
      - build
      - deploy
