version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - checkout
      - run: 
          name: installing nomad
          command: |
            apt-get -y update 
            nomad agent -dev -bind 0.0.0.0 -log-level INFO
      - save_cache:
          key: v1-myapp-cache
          paths:
            - ~/d1

  deploy:
    docker:
      - image: "ubuntu:latest"
    steps:
      - checkout
      - run: sleep 30
      - restore_cache:
          key: v1-myapp-cache
      - run: nomad job init && nomad run example.nomad


workflows:
  build_and_test:
    jobs:
      - build
      - deploy
