version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - run: nomad agent -dev -bind 0.0.0.0 -log-level INFO

  test:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - run: nomad job init
      - run: nomad job run example.nomad


workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build