version: 2.1

jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    steps:
      - run: 
          name: installing nomad
          command: |
            apt-get -y update 
            ARG DEBIAN_FRONTEND="noninteractive" 
            ENV TZ="Etc/UTC" 
            RUN apt-get -y install tzdata 
            apt-get -y install gnome-terminal && gnome-terminal && apt-get -y install nomad && nomad agent -dev -bind 0.0.0.0 -log-level INFO        
      - run: nomad job init && nomad run example.nomad


workflows:
  build_and_test:
    jobs:
      - build
