version: 2.1

jobs:
  build:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python3 basic-add1.py
  test:
    working_directory: ~/circleci-python
    docker:
      - image: "circleci/python:3.8"
    steps:
      - checkout
      - run: python3 basic-add1.py
    docker:
      - image: "circleci/nomad"
    steps:
      - run: nomad status

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build