version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - restore_cache:
          keys: -v1-{{ checksum "dev.txt" }}
      - run: 
          name: installing nomad
          command: |
            apt-get -y update 
            apt-get -y install nomad && nomad agent -dev -bind 0.0.0.0 -log-level INFO
      - save_cache:
          key: -v1-{{ checksum "dev.txt" }}
          paths: 
            - "venv"

  deploy:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - restore_cache:
          key: -v1-{{ checksum "dev.txt" }}
      - run: sleep 30
      - run: nomad job init && nomad run example.nomad

      - save_cache:
          key: -v1-{{ checksum "dev.txt" }}
          paths: 
            - "venv"


workflows:
  build_and_test:
    jobs:
      - build
      - deploy:
          requires:
            - build
