version: 2.1

jobs:
  build:
    docker:
      - image: "circleci/nomad:1.2.0-95-579fc92"
    steps:
      - run: nomad agent -dev -bind 0.0.0.0 -log-level INFO
      - run: gnome-terminal
      - run: nomad job init
      - run: nomad job run example.nomad -bind 0.0.0.0



workflows:
  build_and_test:
    jobs:
      - build
